plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}
	maven {
		name = "Xaero's Maven"
		url = 'https://chocolateminecraft.com/maven'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"voxymap" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modCompileOnly "maven.modrinth:voxy:0.2.15-beta"
	modCompileOnly "maven.modrinth:iris:1.10.7+1.21.11-fabric"
	modCompileOnly "xaero.map:xaeroworldmap-fabric-1.21.11:1.40.16"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "projectName", project.name
	exclude("net/minecraft/client/gui/GuiGraphicsExtractor.class")
	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}

tasks.register("officialRuntimeJar", Jar) {
	dependsOn "classes", "clientClasses"
	archiveFileName = "${project.name}-${project.version}.jar"
	destinationDirectory = layout.buildDirectory.dir("libs")
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	from(sourceSets.main.output)
	from(sourceSets.client.output)
	exclude("net/minecraft/client/gui/GuiGraphicsExtractor.class")
	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}
